// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqotEjqPHzukyeot7omTmGNiqYTR7YYfI',
    appId: '1:735729400105:web:8e2f461a32228cf2ad9f38',
    messagingSenderId: '735729400105',
    projectId: 'agroschoolbusbio',
    authDomain: 'agroschoolbusbio.firebaseapp.com',
    storageBucket: 'agroschoolbusbio.firebasestorage.app',
    measurementId: 'G-5WDQSG5LCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH_anbznmFJ9HBEb15ubkkQ5mPLDGdmIg',
    appId: '1:735729400105:android:00fbadb8aa3fa802ad9f38',
    messagingSenderId: '735729400105',
    projectId: 'agroschoolbusbio',
    storageBucket: 'agroschoolbusbio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANiT-MZqBjz4dyXYq5WSgrfH51jxDfMw0',
    appId: '1:735729400105:ios:b9cb8388ce67e826ad9f38',
    messagingSenderId: '735729400105',
    projectId: 'agroschoolbusbio',
    storageBucket: 'agroschoolbusbio.firebasestorage.app',
    iosBundleId: 'com.analogue.asbtransporter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANiT-MZqBjz4dyXYq5WSgrfH51jxDfMw0',
    appId: '1:735729400105:ios:61d3f80059b5ec65ad9f38',
    messagingSenderId: '735729400105',
    projectId: 'agroschoolbusbio',
    storageBucket: 'agroschoolbusbio.firebasestorage.app',
    iosBundleId: 'com.example.agroschoolbus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqotEjqPHzukyeot7omTmGNiqYTR7YYfI',
    appId: '1:735729400105:web:acb8758e08958658ad9f38',
    messagingSenderId: '735729400105',
    projectId: 'agroschoolbusbio',
    authDomain: 'agroschoolbusbio.firebaseapp.com',
    storageBucket: 'agroschoolbusbio.firebasestorage.app',
    measurementId: 'G-H7CTMFKB1P',
  );

}